name: Reusable workflow example

inputs:
  caller-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Echo from Composite
      run: echo "Hello Mr. ${{ inputs.caller-name }}. How are you?"
