name: Using Composite Actions
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hey DevOps fans!"
  reusable-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: composite-step
        with:
          caller-name: "Bond"
        uses: "./.github/actions/composite"

      - name: composite-step-2
        with:
          caller-name: "Dent"
        uses: "./.github/actions/composite"
