name: Reusable workflow example

on:
  workflow_call:
    inputs:
      caller_name:
        required: true
        type: string

jobs:
  job_name_xyz:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Reusable
        uses: actions/labeler@v4
        run: echo "Hello Mr. {{ inputs.caller_name }}!"
