name: Reusable workflow example

on:
  workflow_call:
    inputs:
      caller_name:
        required: true
        type: string

jobs:
  job-name-xyz:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Reusable
        run: echo "Hello Mr. {{ inputs.caller_name }}. How are you?"
