name: Reusable workflow

on:
  workflow_call:
    inputs:
      caller-name:
        required: true
        type: string

env:
  account: "092882341390"


jobs:
  job_name_abc:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Reusable
        run: echo "Hello Mr. ${{ inputs.caller-name }}. How are you?"
  job_name_xyz:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Reusable
        run: echo "Are you really Mr. ${{ inputs.caller-name }}?"
  composite-from-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: composite-step
        with:
          caller-name: "${{ env.account }}"
        uses: "./.github/actions/composite"
