name: Using Reusable Workflows
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hey DevOps fans!"
  reusable-test:
    with:
      caller-name: "Bond"
    uses: "./.github/reusable/reusable.yaml"
  reusable-test-2:
    with:
      caller-name: "Dent"
    uses: "./.github/reusable/reusable.yaml"
