name: Reusable workflow example

on:
  workflow_call:
    inputs:
      caller-name:
        required: true
        type: string

jobs:
  job_name_xyz:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Reusable
        run: echo "Hello Mr. ${{ inputs.caller-name }}. How are you?"
